INSERT INTO RESERVA VALUES(1,1,103,'2023-01-01','2023-02-02', '2022-12-30');

SELECT * FROM RESERVA


ORDER BY

SELECT NOME FROM CATEGORIA ORDER BY NOME DESC, VALOR_DIA ASC;
SELECT NOME FROM CATEGORIA ORDER BY NOME, VALOR_DIA;
SELECT NOME FROM CATEGORIA ORDER BY NOME DESC; --ASC

--Q28 UNION
SELECT H.NOME FROM HOSPEDE H NATURAL JOIN HOSPEDAGEM HP NATURAL JOIN APARTAMENTO AP JOIN CATEGORIA C 
ON AP.COD_CAT = C.COD_CAT WHERE C.NOME ILIKE 'LUXO' 
UNION
SELECT H.NOME FROM HOSPEDE H NATURAL JOIN RESERVA R NATURAL JOIN APARTAMENTO AP JOIN CATEGORIA C 
ON AP.COD_CAT = C.COD_CAT WHERE C.NOME ILIKE 'LUXO';

--Q30 INTERSECT
SELECT H.NOME FROM HOSPEDE H NATURAL JOIN HOSPEDAGEM HP NATURAL JOIN APARTAMENTO AP JOIN CATEGORIA C 
ON AP.COD_CAT = C.COD_CAT WHERE C.NOME ILIKE 'LUXO' 
INTERSECT
SELECT H.NOME FROM HOSPEDE H NATURAL JOIN RESERVA R NATURAL JOIN APARTAMENTO AP JOIN CATEGORIA C 
ON AP.COD_CAT = C.COD_CAT WHERE C.NOME ILIKE 'LUXO';

--Q27
SELECT NOME FROM HOSPEDE WHERE COD_HOSP NOT IN 
(SELECT COD_HOSP FROM HOSPEDAGEM NATURAL JOIN APARTAMENTO WHERE COD_CAT IN 
 (SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%'));

--EXCEPT

SELECT * FROM (SELECT NOME FROM HOSPEDE) JOIA;

--DATEDIF         

--ADICIONANDO FUNCIONARIO

CREATE TABLE FUNCIONARIO
(COD_FUNC INT NOT NULL PRIMARY KEY,
NOME VARCHAR(20) NOT NULL,
DT_NASC DATE,
SALARIO FLOAT NOT NULL
);

INSERT INTO FUNCIONARIO VALUES
(1, 'JOAZINHO', '2000-03-03', 10000);

ALTER TABLE HOSPEDAGEM 
ADD COLUMN COD_FUNC INT NOT NULL DEFAULT 1
REFERENCES FUNCIONARIO(COD_FUNC);

ALTER TABLE RESERVA 
ADD COLUMN COD_FUNC INT NOT NULL DEFAULT 1
REFERENCES FUNCIONARIO(COD_FUNC);

SELECT * FROM FUNCIONARIO;