SELECT * FROM RESERVA

--1. Categorias que possuam preços entre R$ 100,00 e R$ 200,00.
SELECT nome FROM categoria WHERE VALOR_DIA BETWEEN 100 AND 200;

--2. Categorias cujos nomes possuam a palavra ‘Luxo’.
SELECT NOME FROM CATEGORIA WHERE NOME ILIKE '%LUXO%';

--3. Nomes de categorias de apartamentos que foram ocupados há mais de 5 anos.
SELECT NOME FROM CATEGORIA C, APARTAMENTO A, HOSPEDAGEM H WHERE 
EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DT_SAI) > 5;

--4. Apartamentos que estão ocupados, ou seja, a data de saída está vazia.
SELECT NUM FROM APARTAMENTO WHERE STATUS = 'O';

SELECT H.NUM FROM APARTAMENTO A NATURAL JOIN HOSPEDAGEM H WHERE DT_SAI IS NULL;

--5. Apartamentos cuja categoria tenha código 1, 2, 3, 11, 34, 54, 24, 12.
SELECT NUM FROM APARTAMENTO WHERE COD_CAT IN(1, 2, 3, 11, 34, 54, 24, 12);

--6. Apartamentos cujas categorias iniciam com a palavra ‘Luxo’.
SELECT NOME FROM APARTAMENTO NATURAL JOIN CATEGORIA WHERE NOME ILIKE('LUXO%');

--7. Quantidade de apartamentos cadastrados no sistema.
SELECT COUNT(*) FROM APARTAMENTO;

--8. Somatório dos preços das categorias.
SELECT SUM(VALOR_DIA) FROM CATEGORIA;

--9. Média de preços das categorias.
SELECT AVG(VALOR_DIA) FROM CATEGORIA;

--10. Maior preço de categoria.
SELECT MAX(VALOR_DIA) FROM CATEGORIA;

--11. Menor preço de categoria.
SELECT MIN(VALOR_DIA) FROM CATEGORIA;

--12. O preço média das diárias dos apartamentos ocupados por cada hóspede.
SELECT AVG(C.VALOR_DIA) FROM APARTAMENTO A NATURAL JOIN HOSPEDAGEM H NATURAL JOIN CATEGORIA C GROUP BY COD_HOSP;

--13. Quantidade de apartamentos para cada categoria.
SELECT COUNT(*) FROM APARTAMENTO NATURAL JOIN CATEGORIA GROUP BY NOME;

--14. Categorias que possuem pelo menos 2 apartamentos.
SELECT NOME FROM CATEGORIA NATURAL JOIN APARTAMENTO GROUP BY NOME HAVING COUNT(*)>1;

--15. Nome dos hóspedes que nasceram após 1° de janeiro de 1970.
SELECT NOME FROM HOSPEDE WHERE DT_NASC > '1970-01-01';

--16. Quantidade de hóspedes.
SELECT COUNT(*) FROM HOSPEDE;

--17. Apartamentos que foram ocupados pelo menos 2 vezes.
SELECT NUM FROM APARTAMENTO NATURAL JOIN HOSPEDAGEM GROUP BY NUM HAVING COUNT(*) > 1;

--18. Altere a tabela Hóspede, acrescentando o campo "Nacionalidade".
ALTER TABLE HOSPEDE
ADD COLUMN nacionalidade varchar(50) NOT NULL DEFAULT 'NÃO INFORMADO';

--19.Quantidade de hóspedes para cada nacionalidade.
SELECT COUNT(*) FROM HOSPEDE GROUP BY NACIONALIDADE;

--20. A data de nascimento do hóspede mais velho.
SELECT MIN(DT_NASC) FROM HOSPEDE;

--21. A data de nascimento do hóspede mais novo.
SELECT MAX(DT_NASC) FROM HOSPEDE;

--22. Reajuste em 10% o valor das diárias das categorias.
UPDATE CATEGORIA
SET VALOR_DIA = VALOR_DIA * 1.1;

--23. O nome das categorias que não possuem apartamentos.
SELECT NOME FROM CATEGORIA WHERE NOME NOT IN(
	SELECT DISTINCT NOME FROM CATEGORIA NATURAL JOIN APARTAMENTO);

--24. O número dos apartamentos que nunca foram ocupados.
SELECT NUM FROM APARTAMENTO WHERE NUM NOT IN(
	SELECT DISTINCT NUM FROM APARTAMENTO NATURAL JOIN HOSPEDAGEM);

--25. O número do apartamento mais caro ocupado pelo João.
SELECT MAX(VALOR_DIA) FROM CATEGORIA NATURAL JOIN APARTAMENTO NATURAL JOIN HOSPEDAGEM WHERE COD_HOSP IN
(SELECT COD_HOSP FROM HOSPEDE WHERE NOME ILIKE '%JOÃO%');

--26. O nome dos hóspedes que nunca se hospedaram no apartamento 201.
SELECT NOME FROM HOSPEDE NATURAL JOIN HOSPEDAGEM WHERE NUM <> 201;

--27. O nome dos hóspedes que nunca se hospedaram em apartamentos da categoria LUXO.
SELECT NOME FROM HOSPEDE NATURAL JOIN HOSPEDAGEM NATURAL JOIN APARTAMENTO WHERE COD_CAT NOT IN
(SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%');

SELECT NOME FROM HOSPEDE WHERE COD_HOSP NOT IN 
(SELECT COD_HOSP FROM HOSPEDAGEM NATURAL JOIN APARTAMENTO WHERE COD_CAT IN 
 (SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%'));

--28. O nome dos hóspedes que se hospedaram ou reservaram apartamento do tipo LUXO.
SELECT NOME FROM HOSPEDE NATURAL JOIN HOSPEDAGEM NATURAL JOIN APARTAMENTO WHERE COD_CAT IN
(SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%')
UNION
SELECT NOME FROM HOSPEDE NATURAL JOIN RESERVA NATURAL JOIN APARTAMENTO WHERE COD_CAT IN
(SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%');

--29. O nome dos hóspedes que se hospedaram mas nunca reservaram apartamentos do tipo LUXO.
SELECT DISTINCT NOME FROM HOSPEDE NATURAL JOIN HOSPEDAGEM WHERE NOME NOT IN (
SELECT NOME FROM HOSPEDE NATURAL JOIN APARTAMENTO NATURAL JOIN RESERVA WHERE COD_CAT IN(
SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%'));
		
SELECT DISTINCT H.NOME FROM HOSPEDE H NATURAL JOIN HOSPEDAGEM NATURAL JOIN APARTAMENTO AP JOIN CATEGORIA CA ON AP.COD_CAT = C.CAT WHERE C.NOME ILIKE 'LUXO' AND COD_HOSP NOT IN (SELECT COD_HOSP FROM RESERVA NATURAL JOIN APARTAMENTO NATURAL JOIN CATEGORIA WHERE NOME ILIKE 'LUXO');

--30. O nome dos hóspedes que se hospedaram e reservaram apartamento do tipo LUXO.
SELECT NOME FROM HOSPEDE NATURAL JOIN HOSPEDAGEM NATURAL JOIN APARTAMENTO WHERE COD_CAT IN
(SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%')
INTERSECT
SELECT NOME FROM HOSPEDE NATURAL JOIN RESERVA NATURAL JOIN APARTAMENTO WHERE COD_CAT IN
(SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%');
